# Generated by Django 3.0.7 on 2020-10-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('contactno', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'register',
                'managed': False,
            },
        ),
    ]
